Brais_MVC/Areas/Administrador/Controllers/MasterPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Brais_MVC.Areas.Administrador.Controllers
{
    public class MasterPageController : Controller
    {
        // GET: Administrador/MasterPage
        public ActionResult MasterPage()
        {
            return View();
        }
    }
}

Brais_MVC/Areas/Medico/Controllers/MisDatosController.cs
using Logica.Clases;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Utilitaria.Clases;
using Utilitaria.Clases.Medico;

namespace Brais_MVC.Areas.Medico.Controllers
{
    public class MisDatosController : Controller
    {
        public ActionResult MisDatos()
        {
            return View();
        }

        [HttpPost]
        public JsonResult modificarDatosBasicos(string Correo, string Telefono, Int64 IdMedico, int IdAcceso)
        {
            try
            {
                Respuesta respuesta = LMedico.modificarDatosBasicos(Correo, Telefono, IdMedico, IdAcceso);

                return Json(respuesta);
            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }

        [HttpPost]
        public JsonResult modificarContrasena(string Contrasena, string NuevaContrasena, Int64 IdMedico, int IdAcceso)
        {
            try
            {
                EAcceso eAcceso = LSeguridad.getAcceso(IdAcceso);

                Respuesta respuesta = LMedico.updateContrasena(Contrasena, NuevaContrasena, IdMedico, eAcceso);

                return Json(respuesta);
            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }

        [HttpPost]
        public JsonResult getMedico(int IdAcceso)
        {
            try
            {
                EAcceso eAcceso = LSeguridad.getAcceso(IdAcceso);

                EMedico eMedico = (EMedico)LMedico.get(eAcceso.IdUsuario).Data;

                return Json(Respuesta.newRespuestaCorrecto("", eMedico));
            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }
    }
}

Brais_MVC/Areas/Usuario/Controllers/AsignarCitaController.cs
using Brais_MVC.App_Code;
using Logica.Clases;
using Logica.Clases.Medico;
using Logica.Clases.Usuario;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Utilitaria.Clases;

namespace Brais_MVC.Areas.Usuario.Controllers
{
    public class AsignarCitaController : BaseController
    {

        public ActionResult AsignarCita()
        {
            return View();
        }

        [HttpPost]
        public JsonResult getDDLServicio()
        {
            try
            {
                return Json(Respuesta.newRespuestaCorrecto( "", PartialViewToString(PartialView("_DDLServicio", LEspecialidad.getAll()))));
            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }

        [HttpPost]
        public JsonResult getAsignarCita(int IdAcceso, string Fecha, int IdEspecialidad)
        {
            try
            {
                EAcceso eAcceso = LSeguridad.getAcceso(IdAcceso);
                Respuesta respuesta = LCita.getCitasDisponiblesParaUsuario(eAcceso.IdUsuario, IdEspecialidad, Fecha);

                return Json(respuesta);
            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }

        public JsonResult validarCita(int idCita)
        {
            try
            {
                Respuesta respuesta = LCita.verificarCita(idCita);
                return Json(respuesta);
            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }
    }
}

Brais_MVC/Controllers/MasterPageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Brais_MVC.App_Code;
using Logica.Clases.Administrador;
using Utilitaria.Clases;

namespace Brais_MVC.Controllers
{
    public class MasterPageController : BaseController
    {
        // GET: MasterPage
        public ActionResult MasterPage()
        {
            return View();
        }

    }
}

Brais_MVC/Areas/Usuario/Views/Shared/GV_CitasAgendadas.cshtml
@using Utilitaria.Clases.Usuario;
@model List<ECita>

@if (Model.Count == 0)
{
    <p class="LB_TablaVacia">No hay informacion que mostrar</p>
}
else
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th class="LB_Fecha">Fecha</th>
                <th class="LB_HoraInicio">Hora Inicio</th>
                <th class="LB_HoraFin">Hora Fin</th>
                <th class="LB_servicio">Servicio</th>
                <th class="LB_Estado">Estado</th>
                <th class="LB_Consultorio">Consultorio</th>
                <th class="LB_Medico">Médico</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cita in Model)
            {

            <tr>
                <td>@cita.Fecha</td>
                <td>@cita.HoraInicio</td>
                <td>@cita.HoraInicio</td>
                <td>@cita.Servicio</td>
                <td>@cita.Estado</td>
                <td>@cita.EMedico.EConsultorio.Nombre</td>
                <td>@cita.EMedico.Nombre @cita.EMedico.Apellido</td>
                <td>
                    <button IdCita="@cita.Id" onclick='reprogramarCita(event);' class="material-icons btn btn-primary">calendar_today</button>
                </td>
                <td>
                    <button IdCita="@cita.Id" onclick='eliminarCita(event);' class="material-icons btn btn-warning">delete</button>
                </td>
            </tr>
            }
        </tbody>
    </table>
}

Brais_MVC/Areas/Usuario/Views/Shared/MasterPage.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="~/logo.png" />

    <title>Brais - Usuario</title>

    @Scripts.Render("~/bundles/jquery")
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <link rel="stylesheet" href="~/Content/bootstrap4.min.css">
    <link href="~/Content/main.css" rel="stylesheet" />

    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/General/Constantes.js"></script>
    <script src="~/Scripts/Idioma/Idioma.js"></script>
    <script src="~/Scripts/General/RespuestasServer.js"></script>
    <script src="~/Scripts/General/ValidacionesCampos.js"></script>
    <script src="~/Scripts/Seguridad/SeguridadAcceso.js"></script>
    <script src="~/Scripts/Utilitario/Component.js"></script>

</head>
<body>
    <div class="navbar navbar-expand-sm justify-content-start bg-primary">
        @Html.ActionLink("Asignar cita", "AsignarCita", "AsignarCita", new { area = "Usuario" }, new { @class = "LB_AsignarCita btn btn-primary" })
        @Html.ActionLink("Citas agendadas", "CitasAgendadas", "CitasAgendadas", new { area = "Usuario" }, new { @class = "LB_CitasAgendadas btn btn-primary" })
        @Html.ActionLink("Historial", "Historial", "Historial", new { area = "Usuario" }, new { @class = "LB_Historial btn btn-primary" })
        @Html.ActionLink("Mis datos", "MisDatos", "MisDatos", new { area = "Usuario" }, new { @class = "LB_MisDatos btn btn-primary" })
        @Html.ActionLink("Compramatic", "Compramatic", "Compramatic", new { area = "Usuario" }, new { @class = "btn btn-primary" })
        <button class="LB_CerrarSesion btn btn-danger" onclick="cerrarAcceso()">Cerrar sesion</button>
    </div>

    <div id="mensajes" class="d-inline" style="overflow:auto; right: 0; position:fixed; max-height:25%; z-index: 10;"></div>

    <div class="banner">

    </div>


    <div class="container body-content">
        @RenderBody()
    </div>
</body>
</html>

Brais_MVC/Areas/Usuario/Views/Shared/_C_Fechas.cshtml
@model List<DateTime>

<style>
    #calendar {
        font-family: "latoregular","Trebuchet MS", Arial, Helvetica, sans-serif;
        font-size: 12px;
    }

    #calendar caption {
        text-align: left;
        padding: 5px 10px;
        margin-top: 10px;
        background-color: white;
        color: #3c5281;
        font-weight: bold;
        font-size: medium;
        border-top: 1px solid black;
    }

    #calendar caption div:nth-child(1) {
        float: left;
    }

    #calendar caption div:nth-child(2) {
        float: right;
    }

    #calendar caption div:nth-child(2) a {
        cursor: pointer;
    }

    #calendar th {
        text-align: center;
        margin-top: 10px;
        background-color: white;
        color: #3c5281;
        width: 40px;
        height: 30px;
    }

    #calendar td {
        text-align: center;
        padding: 2px 5px;
        background-color: white;
        color: silver;
        width: 40px;
        height: 30px;
    }

    #calendar .hoy {
        border-width: 2px;
        border-style: solid;
        border-color: red;
    }
</style>


<table id="calendar" ondayrenser="">
    <caption></caption>
    <thead>
        <tr>
            <th style="color:#d0453b">Dom</th>
            <th>Lun</th>
            <th>Mar</th>
            <th>Mie</th>
            <th>Jue</th>
            <th>Vie</th>
            <th style="color:#d0453b">Sab</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

<script>
    var actual = new Date();
    function mostrarCalendario(year, month) {
        var now = new Date(year, month - 1, 1);
        var last = new Date(year, month, 0);
        var primerDiaSemana = ((now.getDay() == 0) ? 7 : now.getDay()) + 1;
        var ultimoDiaMes = last.getDate();
        var dia = 0;
        var resultado = "<tr bgcolor='silver'>";
        var diaActual = 0;
        //console.log(ultimoDiaMes);
        var last_cell = primerDiaSemana + ultimoDiaMes;

        // hacemos un bucle hasta 42, que es el máximo de valores que puede
        // haber... 6 columnas de 7 dias
        for (var i = 1; i <= 42; i++) {
            if (i == primerDiaSemana) {
                // determinamos en que dia empieza
                dia = 1;
            }
            if (i < primerDiaSemana || i >= last_cell) {
                // celda vacia
                resultado += "<td>&nbsp;</td>";
            }
            else {
                // mostramos el dia
                resultado += "<td>" + dia + "</td>";
                dia++;
            }
            if (i % 7 == 0) {
                if (dia > ultimoDiaMes)
                    break;
                resultado += "</tr><tr>\n";
            }
        }
        resultado += "</tr>";

        var meses = Array("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre");

        // Calculamos el siguiente mes y año
        nextMonth = month + 1;
        nextYear = year;
        if (month + 1 > 12) {
            nextMonth = 1;
            nextYear = year + 1;
        }

        // Calculamos el anterior mes y año
        prevMonth = month - 1;
        prevYear = year;
        if (month - 1 < 1) {
            prevMonth = 12;
            prevYear = year - 1;
        }

        document.getElementById("calendar").getElementsByTagName("caption")[0].innerHTML = "<div>" + meses[month - 1] + " / " + year + "</div><div><a onclick='mostrarCalendario(" + prevYear + "," + prevMonth + ")'>&lt;</a> <a onclick='mostrarCalendario(" + nextYear + "," + nextMonth + ")'>&gt;</a></div>";
        document.getElementById("calendar").getElementsByTagName("tbody")[0].innerHTML = resultado;
    }

    mostrarCalendario(actual.getFullYear(), actual.getMonth() + 1);

</script>

Brais_MVC/Areas/Usuario/Views/Shared/_DDLServicio.cshtml
@using Utilitaria.Clases.Medico

@model List<EEspecialidad>

@if (Model.Count != 0)
{
    <div class="form-group">
        <select id="Especialidad" name="Especialidad" class="form-control campo_vacio">
            <option class="LB_Seleccione" value="0">Seleccione</option>
            @foreach (var especialidad in Model)
            {
                <option value="@especialidad.Id">@especialidad.Nombre</option>
            }
        </select>
    </div>
}

<script>

    @*DDL_Servicio.change(
        function (event) {
            event.preventDefault();
            var url = "@Url.Action("actualizarDiasDisponibles", "AsignarCita", new { area = "Usuario" })";

            //console.log($("#Especialidad option:selected").text());
            var data = {
                idEspecialidad: $("#Especialidad option:selected").val()
            }

            $.post(url, data).done(
                function (respuesta) {
                    if (respuesta.Estado == MENSAJE_CORRECTO) {
                        console.log($("#Especialidad option:selected").text());
                    }
                    mostrarMensajeRespuestaPost(respuesta);
                }
            ).fail(mostrarErrorRespuestaPost)
        }
    );*@
</script>