Brais_MVC/Areas/Administrador/Controllers/MasterPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Brais_MVC.Areas.Administrador.Controllers
{
    public class MasterPageController : Controller
    {
        // GET: Administrador/MasterPage
        public ActionResult MasterPage()
        {
            return View();
        }
    }
}

Brais_MVC/Areas/Medico/Controllers/MisDatosController.cs
using Logica.Clases;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Utilitaria.Clases;
using Utilitaria.Clases.Medico;

namespace Brais_MVC.Areas.Medico.Controllers
{
    public class MisDatosController : Controller
    {
        public ActionResult MisDatos()
        {
            return View();
        }

        [HttpPost]
        public JsonResult modificarDatosBasicos(string Correo, string Telefono, Int64 IdMedico, int IdAcceso)
        {
            try
            {
                Respuesta respuesta = LMedico.modificarDatosBasicos(Correo, Telefono, IdMedico, IdAcceso);

                return Json(respuesta);
            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }

        [HttpPost]
        public JsonResult modificarContrasena(string Contrasena, string NuevaContrasena, Int64 IdMedico, int IdAcceso)
        {
            try
            {
                EAcceso eAcceso = LSeguridad.getAcceso(IdAcceso);

                Respuesta respuesta = LMedico.updateContrasena(Contrasena, NuevaContrasena, IdMedico, eAcceso);

                return Json(respuesta);
            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }

        [HttpPost]
        public JsonResult getMedico(int IdAcceso)
        {
            try
            {
                EAcceso eAcceso = LSeguridad.getAcceso(IdAcceso);

                EMedico eMedico = (EMedico)LMedico.get(eAcceso.IdUsuario).Data;

                return Json(Respuesta.newRespuestaCorrecto("", eMedico));
            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }
    }
}

Brais_MVC/Areas/Medico/Controllers/PlatoWebController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Utilitaria.Clases;
using Utilitaria.Clases.Servicios;

namespace Brais_MVC.Areas.Medico.Controllers
{
    public class PlatoWebController : Controller
    {
        // GET: Medico/PlatoWeb
        public ActionResult PlatoWeb()
        {
            return View();
        }

        [HttpPost]
        public JsonResult traerMenu()
        {
            //ReservaPlato reservaPlato = new ReservaPlato();
            //String menu = reservaPlato.traerMenu();

            try
            {
                ServiciosPlatoWeb.ServiciosSoapClient servicio = new ServiciosPlatoWeb.ServiciosSoapClient();

                ServiciosPlatoWeb.Seguridad obSeguridad = new ServiciosPlatoWeb.Seguridad()
                {
                    stToken = DateTime.Now.ToString("yyyyMMdd")
                };

                String StToken = servicio.AutenticationUsuario(obSeguridad);
                if (StToken.Equals("-1")) throw new Exception("Requiere Validacion");

                obSeguridad.AutenticationToken = StToken;

                String menu = servicio.LMenu(obSeguridad);

                JArray menuJArray = JArray.Parse(menu);

                List<PlatoWeb> platos = new List<PlatoWeb>();

                foreach (var item in menuJArray.Children())
                {
                    PlatoWeb platoWeb = new PlatoWeb();

                    platoWeb.Id = int.Parse(item["id"].ToString());
                    platoWeb.Nombre = item["nombre"].ToString();
                    platoWeb.Descripcion = item["descripcion"].ToString();
                    platoWeb.Precio = item["precio"].ToString();
                    platoWeb.Imagen = item["imagen"].ToString();

                    platos.Add(platoWeb);
                }

                return Json(Respuesta.newRespuestaCorrecto("", platos));

            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }

        [HttpPost]
        public JsonResult reservarPlato(String Fecha, String Hora, int CantidadPersonas, int IdPlato)
        {
            try
            {
                ServiciosPlatoWeb.ServiciosSoapClient servicio = new ServiciosPlatoWeb.ServiciosSoapClient();

                ServiciosPlatoWeb.Seguridad obSeguridad = new ServiciosPlatoWeb.Seguridad()
                {
                    stToken = DateTime.Now.ToString("yyyyMMdd")
                };

                String StToken = servicio.AutenticationUsuario(obSeguridad);
                if (StToken.Equals("-1")) throw new Exception("Requiere Validacion");

                obSeguridad.AutenticationToken = StToken;

                //DataTable data =  servicio.Login(obSeguridad, "pepitopaciente", "2");

                servicio.Reserva(obSeguridad, Fecha, Hora, CantidadPersonas, IdPlato.ToString());

                return Json("Reserva programada");
            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }

        [HttpPost]
        public JsonResult contactosPlatoWeb(String Nombre, String Email, String Telefono, String Detalle)
        {
            try
            {
                ServiciosPlatoWeb.ServiciosSoapClient servicio = new ServiciosPlatoWeb.ServiciosSoapClient();

                ServiciosPlatoWeb.Seguridad obSeguridad = new ServiciosPlatoWeb.Seguridad()
                {
                    stToken = DateTime.Now.ToString("yyyyMMdd")
                };

                String StToken = servicio.AutenticationUsuario(obSeguridad);
                if (StToken.Equals("-1")) throw new Exception("Requiere Validacion");

                obSeguridad.AutenticationToken = StToken;

                servicio.Contactenos(obSeguridad, Nombre, Email, Telefono, Detalle);

                return Json("Mensaje enviado a Plato a la Web");

            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }
    }
}

Brais_MVC/Controllers/MasterPageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Brais_MVC.App_Code;
using Logica.Clases.Administrador;
using Utilitaria.Clases;

namespace Brais_MVC.Controllers
{
    public class MasterPageController : BaseController
    {
        // GET: MasterPage
        public ActionResult MasterPage()
        {
            return View();
        }

    }
}

Brais_MVC/Areas/Medico/Views/Shared/MasterPage.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="~/logo.png" />

    <title>Brais - Medico</title>

    @Scripts.Render("~/bundles/jquery")
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="~/Content/bootstrap4.min.css">
    <link href="~/Content/main.css" rel="stylesheet" />

    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/General/Constantes.js"></script>
    <script src="~/Scripts/Idioma/Idioma.js"></script>
    <script src="~/Scripts/General/RespuestasServer.js"></script>
    <script src="~/Scripts/General/ValidacionesCampos.js"></script>
    <script src="~/Scripts/Seguridad/SeguridadAcceso.js"></script>

</head>
<body>
    <div class="navbar navbar-expand-sm justify-content-start bg-dark">
        @Html.ActionLink("Agenda", "Agenda", "Agenda", new { area = "Medico" }, new { @class = "LB_Agenda btn btn-primary" })
        @Html.ActionLink("Historial", "Historial", "Historial", new { area = "Medico" }, new { @class = "LB_Historial btn btn-primary" })
        @Html.ActionLink("Horario", "Horario", "Horario", new { area = "Medico" }, new { @class = "LB_Horario btn btn-primary" })
        @Html.ActionLink("Mis datos", "MisDatos", "MisDatos", new { area = "Medico" }, new { @class = "LB_MisDatos btn btn-primary" })
        @Html.ActionLink("Reservar Comida", "PlatoWeb", "PlatoWeb", new { area = "Medico" }, new { @class = "LB_PlatoWeb btn btn-primary" })
        <button class="LB_CerrarSesion btn btn-danger" onclick="cerrarAcceso()">Cerrar sesion</button>
    </div>

    <div id="mensajes" class="d-inline" style="overflow:auto; right: 0; position:fixed; max-height:25%; z-index: 10;"></div>

    <div class="container body-content">
        @RenderBody()
    </div>
</body>
</html>