Brais_MVC/Areas/Medico/Controllers/HorarioController.cs
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using Logica.Clases;
using Logica.Clases.Medico;
using Logica.Clases.Usuario;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Utilitaria.Clases;
using Utilitaria.Clases.Medico;

namespace Brais_MVC.Areas.Medico.Controllers
{
    public class HorarioController : Controller
    {
        public ActionResult Horario()
        {
            return View();
        }
        
        [HttpPost]
        public JsonResult getHorario(int IdAcceso)
        {
            try
            {
                EAcceso eAcceso = LSeguridad.getAcceso(IdAcceso);

                EMedico eMedico = (EMedico)LMedico.get(eAcceso.IdUsuario).Data;

                return Json(Respuesta.newRespuestaCorrecto("", eMedico.Horario));
            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }

        [HttpPost]
        public JsonResult guardarHorario(Horario horario, int IdAcceso)
        {
            try
            {
                EAcceso eAcceso = LSeguridad.getAcceso(IdAcceso);

                Respuesta respuesta = LMedico.modificarHorario(horario, eAcceso.IdUsuario, eAcceso);

                return Json(respuesta);
            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }

        [HttpPost]
        public JsonResult generarCitas(int IdAcceso)
        {
            try
            {
                EAcceso eAcceso = LSeguridad.getAcceso(IdAcceso);

                EMedico eMedico = (EMedico)LMedico.get(eAcceso.IdUsuario).Data;

                Respuesta respuesta = LCita.generarcCitasMedico(eMedico, eAcceso);

                return Json(respuesta);
            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }

        [HttpPost]
        public JsonResult solicitarReporte(int IdAcceso)
        {
            try
            {
                EAcceso eAcceso = LSeguridad.getAcceso(IdAcceso);

                Session["Id_Medico_Reporte"] = eAcceso.IdUsuario;

                return Json(Respuesta.newRespuestaCorrecto(""));
            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }

        public ActionResult reporte()
        {
            ReportDocument report = new ReportDocument();
            var ruta = Server.MapPath("~/Reportes/Medico/CR_Horario.rpt");

            report.Load(ruta);

            Int64 idMedico = Int64.Parse(Session["Id_Medico_Reporte"].ToString());

            EMedico eMedico = (EMedico)LMedico.get(idMedico).Data;

            List<ReporteHorario> reportehorarios = LReportesMedico.dataHorario(eMedico.Horario);

            report.SetDataSource(reportehorarios);
            Stream stream = report.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            return File(stream, "application/pdf");
        }
    }
}

Brais_MVC/Areas/Medico/Views/Horario/Horario.cshtml
@{
    Layout = "~/Areas/Medico/Views/Shared/MasterPage.cshtml";
}

<div class="p-4">
    <form id="FormRango" class="card m-auto" style="max-width:300px;">
        <div class="card-header">
            <h4 class="LB_Rango text-center">Rango</h4>
        </div>

        <div class="card-body">
            <div class="form-group">
                <label class="LB_Dia">Dia</label>
                <select id="DDL_Dias" name="DDL_Dias" class="form-control campo_vacio">
                    <option class="LB_Seleccione" value="">Seleccione</option>
                    <option disabled class="LB_Lunes" value="1">Lunes</option>
                    <option disabled class="LB_Martes" value="2">Martes</option>
                    <option disabled class="LB_Miercoles" value="3">Miercoles</option>
                    <option disabled class="LB_Jueves" value="4">Jueves</option>
                    <option disabled class="LB_Viernes" value="5">Viernes</option>
                    <option disabled class="LB_Sabado" value="6">Sabado</option>
                    <option disabled class="LB_Domingo" value="0">Domingo</option>
                </select>
            </div>

            <div class="form-group">
                <label class="LB_HoraInicio">Hora inicio</label>
                <select id="DDL_HoraInicio" class="form-control"></select>
            </div>

            <div class="form-group">
                <label class="LB_HoraFin">Hora fin</label>
                <select id="DDL_HoraFin" class="form-control"></select>
            </div>
        </div>

        <div class="card-footer">
            <div class="d-flex justify-content-center">
                <button class="material-icons btn btn-success">add</button>
            </div>
        </div>
    </form>
</div>

<a id="BTN_GenerarReporte" style="display:none;" target="_blank" href="@Url.Action("reporte", "Horario", new { area="Medico" })"></a>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-8">
                <h4 class="LB_Horario text-center">Horario</h4>
            </div>

            <div class="col-md-4 d-flex justify-content-center">
                <button id="BTN_Generar" class="LB_GenerarCitas btn btn-info mr-3">Generar citas</button>

                <button id="BTN_Reporte" class="material-icons btn btn-warning">assignment</button>

                <button id="BTN_Guardar" class="material-icons btn btn-success mr-3">save</button>
            </div>
        </div>
    </div>

    <div class="card-body">
        <div id="ContenedorHorario" class="d-flex justify-content-center flex-wrap">
            <div class="card" id="1">
                <div class="card-header">
                    <h5 class="LB_Lunes">Lunes</h5>
                </div>

                <div class="card-body">

                </div>
            </div>
            <div class="card" id="2">
                <div class="card-header">
                    <h5 class="LB_Martes">Martes</h5>
                </div>

                <div class="card-body">

                </div>
            </div>
            <div class="card" id="3">
                <div class="card-header">
                    <h5 class="LB_Miercoles">Miercoles</h5>
                </div>

                <div class="card-body">

                </div>
            </div>
            <div class="card" id="4">
                <div class="card-header">
                    <h5 class="LB_Jueves">Jueves</h5>
                </div>

                <div class="card-body">

                </div>
            </div>
            <div class="card" id="5">
                <div class="card-header">
                    <h5 class="LB_Viernes">Viernes</h5>
                </div>

                <div class="card-body">

                </div>
            </div>
            <div class="card" id="6">
                <div class="card-header">
                    <h5 class="LB_Sabado">Sabado</h5>
                </div>

                <div class="card-body">

                </div>
            </div>
            <div class="card" id="0">
                <div class="card-header">
                    <h5 class="LB_Domingo">Domingo</h5>
                </div>

                <div class="card-body">

                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .rango{
        display: flex;
        align-items: center;
        margin-bottom: 3px;
        border-bottom: solid gray;
    }

    .rango button{
        margin-left: 6px;
        padding: 0.5px 2px;
    }
</style>

<script src="~/Scripts/moment.min.js"></script>

<script>
    var FormRango = $("#FormRango");
    var DDL_Dias = document.getElementById("DDL_Dias");
    var DDL_HoraInicio = document.getElementById("DDL_HoraInicio");
    var DDL_HoraFin = document.getElementById("DDL_HoraFin");
    var horario = null;
    var parametros = null;
    var BTN_Guardar = $("#BTN_Guardar");
    var BTN_Generar = $("#BTN_Generar");
    var BTN_Reporte = $("#BTN_Reporte");
    var BTN_GenerarReporte = $("#BTN_GenerarReporte");

    BTN_Guardar.hide();
    BTN_Guardar.click(guardarHorarioClick);

    BTN_Generar.click(generarCitasClik);
    BTN_Reporte.click(reporteClick);

    DDL_HoraInicio.addEventListener("change", function (e) { cargarHoraFin(); });

    getParametros();
    getHorario();

    FormRango.submit(
        function (event) {
            event.preventDefault();

            FormRango.validate();

            if (FormRango.valid()) {

                var dia = parseInt(DDL_Dias.options[DDL_Dias.selectedIndex].value);
                var horaInicio = DDL_HoraInicio.options[DDL_HoraInicio.selectedIndex].value;
                var horaFin = DDL_HoraFin.options[DDL_HoraFin.selectedIndex].value;

                var rango = {
                    Dia: dia,
                    Inicio: horaInicio,
                    Fin: horaFin
                }

                agregarRango(rango);
            }
        }
    );

    function agregarRango(rango) {
        if (!elRangoSeCruza(rango)) {
            horario.Rangos.push(rango);
            mostrarHorario();
            BTN_Guardar.show();
            BTN_Generar.hide();
            BTN_Reporte.hide();
        }
        else {
            mostrarMensaje({ Estado: MENSAJE_ALERTA, Mensaje: "El rango se cruza"});
        }
    }

    function elRangoSeCruza(rango) {
        var inicioA = moment(rango.Inicio, "HH:mm");
        var finA = moment(rango.Fin, "HH:mm");

        for (var i = 0; i < horario.Rangos.length; i++) {
            var r = horario.Rangos[i];

            if (r.Dia == rango.Dia) {
                var inicioB = moment(r.Inicio, "HH:mm");
                var finB = moment(r.Fin, "HH:mm");

                if ((inicioB < inicioA && inicioA < finB) || (inicioB < finA && finA < finB) ||
                    (inicioA < inicioB && inicioB < finA) || (inicioA < finB && finB < finA) ||
                    (r.Inicio == rango.Inicio && r.Fin == rango.Fin && r.Dia == rango.Dia)) {

                    return true;
                }
            }
        }

        return false;
    }

    function eliminarRango(rango) {
        for (var i = 0; i < horario.Rangos.length; i++) {
            r = horario.Rangos[i];

            if (r.Dia == rango.Dia && r.Inicio == rango.Inicio && r.Fin == rango.Fin) {
                horario.Rangos.splice(i, 1);
                mostrarHorario();
                BTN_Guardar.show();
                BTN_Generar.hide();
                BTN_Reporte.hide();
                break;
            }
        }
    }

    function eliminarRangoClick(event) {
        var rango = JSON.parse(event.target.getAttribute("rango"));
        eliminarRango(rango);
    }

    function activarDias() {
        if (parametros) {
            parametros.DiasLaborales.forEach(function (element, index) {
                DDL_Dias.querySelector("option[value='" + element + "']").disabled = false;
            });
        }
    }

    function cargarHoraInicio() {
        if (parametros) {
            var hora = moment(parametros.HoraInicio, "HH:mm");
            var horaFin = moment(parametros.HoraFin, "HH:mm");

            DDL_HoraInicio.innerHTML = "";

            while (hora < horaFin) {
                var option = document.createElement("option");
                option.textContent = hora.format("hh:mm a");
                option.value = hora.format("HH:mm");

                DDL_HoraInicio.appendChild(option);
                hora = hora.add(1, "hours");
            }
        }
    }

    function cargarHoraFin() {
        if (parametros) {
            var optionDDLInicio = DDL_HoraInicio.options[DDL_HoraInicio.selectedIndex];
            var hora = moment(optionDDLInicio.value, "HH:mm").add(1, "hours");
            var horaFin = moment(parametros.HoraFin, "HH:mm");

            DDL_HoraFin.innerHTML = "";

            while (hora <= horaFin) {
                var option = document.createElement("option");
                option.textContent = hora.format("hh:mm a");
                option.value = hora.format("HH:mm");

                DDL_HoraFin.appendChild(option);
                hora = hora.add(1, "hours");
            }
        }
    }

    function mostrarHorario() {

        document.getElementById("ContenedorHorario").querySelectorAll("div.card-body").forEach(
            function (element) {
                element.innerHTML = "";
            }
        );

        horario.Rangos.forEach(
            function (rango) {
                var div = document.createElement("div");
                div.classList.add("rango");

                var divAux = document.createElement("div");

                var hInicio = document.createElement("h6");
                hInicio.textContent = moment(rango.Inicio, "HH:mm").format("hh:mm a");

                var hFin = document.createElement("h6");
                hFin.textContent = moment(rango.Fin, "HH:mm").format("hh:mm a");

                divAux.appendChild(hInicio);
                divAux.appendChild(hFin);

                var btn = document.createElement("button");
                btn.className = "material-icons btn btn-danger btn-sm";
                btn.innerHTML = "close";
                btn.setAttribute("rango", JSON.stringify(rango));
                btn.onclick = eliminarRangoClick;

                div.appendChild(divAux);
                div.appendChild(btn);

                var cardBody = document.getElementById(rango.Dia).getElementsByClassName("card-body")[0];

                cardBody.appendChild(div);
            }
        );
    }

    function getParametros() {
        var url = "@Url.Action("getParametros", "Parametros", new { area="Administrador" })";

        $.post(url).done(
            function (respuesta) {
                if (respuesta.Estado == MENSAJE_CORRECTO) {
                    parametros = respuesta.Data;
                    activarDias();
                    cargarHoraInicio();
                    cargarHoraFin();
                }

                mostrarMensajeRespuestaPost(respuesta);
            }
        ).fail(mostrarErrorRespuestaPost);
    }

    function getHorario() {
        var url = "@Url.Action("getHorario", "Horario", new { area = "Medico" })";

        var data = {
            IdAcceso: getAcceso().Id
        }

        $.post(url, data).done(
            function (respuesta) {
                if (respuesta.Estado == MENSAJE_CORRECTO) {
                    horario = respuesta.Data;
                    mostrarHorario();
                }
            }
        ).fail(mostrarErrorRespuestaPost);
    }

    function guardarHorarioClick(event) {
        event.preventDefault();
        guardarHorario();
    }

    function guardarHorario() {
        BTN_Guardar.attr("disabled", "disabled");

        var url = "@Url.Action("guardarHorario", "Horario", new { area="Medico" })";

        var data = {
            horario: horario,
            IdAcceso: getAcceso().Id
        }

        $.post(url, data).done(
            function (respuesta) {
                if (respuesta.Estado == MENSAJE_CORRECTO) {
                    getHorario();
                    BTN_Guardar.removeAttr("disabled");
                    BTN_Guardar.hide();
                    BTN_Generar.show();
                    BTN_Reporte.show();
                }

                mostrarMensajeRespuestaPost(respuesta);
            }
        ).fail(mostrarErrorRespuestaPost);
    }

    function generarCitasClik(event) {
        event.preventDefault();
        generarCitas();
    }

    function generarCitas() {
        var url = "@Url.Action("generarCitas", "Horario", new { area="Medico" })";

        var data = {
            IdAcceso: getAcceso().Id
        }

        $.post(url, data).done(mostrarMensajeRespuestaPost).fail(mostrarErrorRespuestaPost);
    }

    function reporteClick(event) {
        event.preventDefault();
        solicitarReporte();
    }

    function solicitarReporte() {
        var url = "/Medico/Horario/solicitarReporte";

        $.post("/Medico/Horario/solicitarReporte", { IdAcceso: getAcceso().Id }).done(
            function (respuesta) {
                if (respuesta.Estado == MENSAJE_CORRECTO) {
                    console.log(BTN_GenerarReporte);
                    BTN_GenerarReporte[0].click();
                }
                mostrarMensajeRespuestaPost(respuesta);
            }
        ).fail(mostrarErrorRespuestaPost);
    }
</script>