Brais_MVC/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Utilitaria.Clases;
using Logica.Clases;

namespace Brais_MVC.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public JsonResult IniciarSesion(string Identificacion, string Contrasena)
        {
            try
            {
                Respuesta respuesta = LFuncion.iniciarSesionMVC(Identificacion, Contrasena);
                
                return Json(respuesta);
            }
            catch (Exception ex)
            {
                return Json(Respuesta.newRespuestaAlerta(ex.Message));
            }
        }
    }
}

Brais_MVC/Views/Login/Login.cshtml
@{
    Layout = "~/Views/MasterPage/MasterPage.cshtml";
}

<h2 class="text-center p-4 LB_Acceder">Acceder</h2>

<form id="form-login" class="d-flex flex-column max-width-form">
    <div class="form-group">
        <label class="LB_Identificacion">Identificacion:</label>
        <input id="Identificacion" name="Identificacion" class="campo_vacio solo_numeros caracteres_especiales form-control" type="text" maxlength="15"/>
    </div>

    <div class="form-group">
        <label class="LB_Contrasena">Contraseña:</label>
        <input id="Contrasena" name="Contrasena" class="contrasena_vacio caracteres_especiales form-control" type="password" maxlength="15"/>
    </div>

    <a href="@Url.Action("RecuperarContrasenaPasoUno", "RecuperarContrasenaPasoUno")" class="LB_OlvidoSuContrasena p-3">¿Olvido su contraseña?</a>


    <button id="BTN_Login" type="submit" class="material-icons btn btn-success align-self-center">check</button>
</form>

<script>
    var BTN_Login = document.getElementById("BTN_Login");

    $("#form-login").submit(
        function (e) {
            e.preventDefault();

            $("#form-login").validate();

            if ($("#form-login").valid()) {
                var url = "@Url.Action("IniciarSesion", "Login")";

                var identificacion = $("#Identificacion").val().trim();
                var contrasena = $("#Contrasena").val();

                var data = {
                    Identificacion: identificacion,
                    Contrasena: contrasena
                }

                BTN_Login.setAttribute("disabled", "disabled");
                $.post(url, data).done(
                    function (respuesta) {
                        if (respuesta.Estado == MENSAJE_CORRECTO) {

                            console.log(respuesta.Data);

                            localStorage.setItem("Acceso", JSON.stringify(respuesta.Data));

                            if (respuesta.Mensaje == "administrador") {
                                window.location = "@Url.Action("VerUsuarios", "VerUsuarios", new { area="Administrador" })";
                            }
                            else if (respuesta.Mensaje == "medico") {
                                window.location = "@Url.Action("Agenda", "Agenda", new { area="Medico" })";
                            }
                            else if (respuesta.Mensaje == "usuario") {
                                window.location = "@Url.Action("AsignarCita", "AsignarCita", new { area="Usuario" })";
                            }
                        }
                        else {
                            mostrarMensajeRespuestaPost(respuesta);
                        }
                        BTN_Login.removeAttribute("disabled");
                    }).fail(mostrarErrorRespuestaPost);
            }
        });
</script>